### ISSUE TITLE
Call out that unique StreamID is treated as unique CloudWatch metric in README

### ISSUE THREAD

**Issue by renlon** [awslabs/cloudwatch-fluent-metrics#15]
I would suggest call out that unique StreamID (unique dimension) is treated as unique CloudWatch metric in README which will incur cost from CloudWatch. 
Currently, it seems that if user do not override the StreamID, FluentMetric will generate unique IDs for dimension StreamID for each metric that it try to put. In which case, it generates way more metrics that the user intent to create.

**Comment by troylar** [comment]
@renlon That's a good call . . . I'll update the docs.

**Comment by troylar** [comment]
@renlon I updated the README -- let me know if that's not clear enough.

**Comment by grvhi** [comment]
@troylar - Sorry for commenting on a closed issue (and for the unsolicited mention!), but I'd be grateful for an explanation as to the what and why of the StreamID dimension..? 

I'm reasonably new to CloudWatch metrics, so I could be missing something, but I don't think this is required by the CWM API? It seems to be a non-optional dimension applied by this library? Which, if I understand correctly, means that every metric created through the library will have to have at least one dimension, making querying the metrics a touch more complicated...

Would it make sense to make including a StreamID optional? And if that doesn't make sense, would it be reasonable for an application to set a constant value for StreamID across all invocations of the application?

Thank you!
