### ISSUE TITLE
Does cloudwatch-fluent-metrics supports High-Resolution Custom Metrics?

### ISSUE THREAD

**Issue by charleswhchan** [awslabs/cloudwatch-fluent-metrics#2]
Announcement:
https://aws.amazon.com/about-aws/whats-new/2017/07/amazon-cloudwatch-introduces-high-resolution-custom-metrics-and-alarms/

I want to use cloudwatch-fluent-metrics to log Kinesis consumer stats at 1s resolution, but then I saw the following in README:
>Values
>
>Obviously we need to log a value with each metric. This needs to be a number since we convert this value to a float before sending to CloudWatch. IMPORTANT: When logging multiple values for the same custom metric within a minute, CloudWatch aggregates an average over a minute. Click [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html#publishingDataPoints) for more details.

I see boto3's CloudWatch [put_metric_data()](http://boto3.readthedocs.io/en/latest/reference/services/cloudwatch.html#CloudWatch.Client.put_metric_data) has a StorageResolution field
> StorageResolution (integer) --
> Valid values are 1 and 60. Setting this to 1 specifies this metric as a high-resolution metric, so that CloudWatch stores the metric with sub-minute resolution down to one second. Setting this to 60 specifies this metric as a regular-resolution metric, which CloudWatch stores at 1-minute resolution. Currently, high resolution is available only for custom metrics. For more information about high-resolution metrics, see High-Resolution Metrics in the Amazon CloudWatch User Guide .
>
>This field is optional, if you do not specify it the default of 60 is used.

Does cloudwatch-fluent-metrics support metrics @ 1s resolution?

Thanks

**Comment by troylar** [comment]
It does not support this. Currently looking into this.

**Comment by troylar** [comment]
I've added support for high-resolution metrics . . .

**Comment by charleswhchan** [comment]
Thanks @troylar
