### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by zamponotiropita** [awslabs/cloudwatch-fluent-metrics#21]
Please support python3. Should be straight forward.

```python
full_pages = len(buffer) / PAGE_SIZE
      for i in range(full_pages):
```

->

```
fluentmetrics/buffer.py in flush at line 60:
'float' object cannot be interpreted as an integer
```

**Comment by zamponotiropita** [comment]
Just figured out that this problem exists only in the current pip version and not in the newest master commit

**Comment by troylar** [comment]
I've re-deployed that latest, so please try again.
